/**
 * Industry Profiles — Frontend mirror of src/utils/industry_config.py
 *
 * This is the LOCAL fallback used before settings load from the API.
 * Once settings load, the backend-provided industry_profile takes precedence
 * (via IndustryContext). This file ensures the UI never flashes wrong labels.
 *
 * To add a new industry:
 *   1. Add an entry here
 *   2. Add a matching entry in src/utils/industry_config.py (backend)
 *   3. Create a prompt file in prompts/<key>_prompt.txt
 */

const industryProfiles = {
  trades: {
    label: 'Trades & Home Services',
    terminology: {
      job: 'Job',
      jobs: 'Jobs',
      employee: 'Employee',
      employees: 'Employees',
      client: 'Customer',
      clients: 'Customers',
      service: 'Service',
      services: 'Services',
      booking: 'Booking',
      // Tab labels — used by Dashboard to render sidebar/nav
      servicesTab: 'Services',
      inventoryTab: 'Inventory',
      financesTab: 'Finances',
      insightsTab: 'Insights',
      calendarTab: 'Calendar',
      callsTab: 'Calls',
      crmTab: 'CRM',
    },
    features: {
      materials: true,
      callouts: true,
      quotes: true,
      emergencyJobs: true,
      propertyType: true,
      jobAddress: true,
      jobPhotos: true,
      multiDayJobs: true,
    },
    tabs: {
      jobs: true,
      calls: true,
      calendar: true,
      employees: true,
      crm: true,
      services: true,
      inventory: true,
      finances: true,
      insights: true,
    },
    icons: {
      employee: 'fas fa-hard-hat',
      job: 'fas fa-briefcase',
    },
    // ─── Service-specific config ─────────────────────────────────────
    serviceConfig: {
      // Categories for grouping services in the list
      categories: [
        'Plumbing', 'Electrical', 'Heating', 'Carpentry', 'Painting',
        'Roofing', 'Drainage', 'General', 'Emergency', 'Other',
      ],
      // Tag presets (certifications, qualifications, attributes)
      tagPresets: [
        'Gas Safe', 'Part P Certified', 'RECI Registered', 'SEAI Registered',
        'Insured', 'Warranty Included', 'Free Quote', 'Same Day',
        'Weekend Available', 'After Hours',
      ],
      tagLabel: 'Certifications & Tags',
      tagPlaceholder: 'e.g., Gas Safe, Insured',
      // Which fields to show in the service form
      showCategory: true,
      showTags: true,
      showCapacity: false,       // trades don't need party size
      showArea: false,            // trades don't need table/section
      showDeposit: true,
      showWarranty: true,
      showSeasonal: true,
      showAiNotes: true,
      showFollowUp: true,
      // Labels
      capacityLabel: '',
      capacityMinLabel: '',
      capacityMaxLabel: '',
      areaLabel: '',
      areaOptions: [],
      warrantyLabel: 'Warranty / Guarantee',
      warrantyPlaceholder: 'e.g., 12-month guarantee on all work',
      depositLabel: 'Deposit Required',
      depositHint: 'Require a deposit before confirming the booking',
      seasonalLabel: 'Seasonal Service',
      seasonalHint: 'Only available during certain months',
      aiNotesLabel: 'Notes for AI',
      aiNotesPlaceholder: 'e.g., Requires scaffolding for 2-storey, always mention warranty',
      followUpLabel: 'Follow-up Service',
      followUpHint: 'After a callout/quote, suggest this service next',
      // Duration filter — which groups to show
      durationGroups: ['Hours', 'Days', 'Working Weeks'],
      // Default icon for service cards
      defaultServiceIcon: 'fa-wrench',
      emptyIcon: '🔧',
      emptyTitle: 'No services yet',
      emptyDescription: 'Add the services you offer. The AI receptionist will use these to match customer requests and book jobs.',
    },
    inventory: {
      categories: [
        'Pipe & Fittings', 'Valves', 'Sealants & Adhesives', 'Fixtures',
        'Electrical', 'Tools & Consumables', 'Heating', 'Drainage',
        'Lumber & Wood', 'Fasteners', 'Paint & Coatings', 'Insulation',
        'Safety Equipment', 'Other',
      ],
      units: [
        { value: 'each', label: 'Each' },
        { value: 'm', label: 'Metre (m)' },
        { value: 'ft', label: 'Foot (ft)' },
        { value: 'kg', label: 'Kilogram (kg)' },
        { value: 'litre', label: 'Litre' },
        { value: 'roll', label: 'Roll' },
        { value: 'box', label: 'Box' },
        { value: 'pack', label: 'Pack' },
        { value: 'pair', label: 'Pair' },
        { value: 'set', label: 'Set' },
        { value: 'length', label: 'Length' },
        { value: 'bag', label: 'Bag' },
        { value: 'tube', label: 'Tube' },
        { value: 'tin', label: 'Tin' },
        { value: 'sheet', label: 'Sheet' },
        { value: 'hour', label: 'Hour' },
      ],
      showCostPrice: true,
      showExpiry: false,
      showBatchNumber: false,
      showLocation: true,
      locationLabel: 'Location',
      locationPlaceholder: 'e.g., Van 1, Warehouse, Site',
      itemLabel: 'Item',
      emptyIcon: '🔧',
      emptyTitle: 'No inventory items yet',
      emptyDescription: 'Add the parts and materials you use on jobs. Track stock levels, costs, and set reorder alerts.',
      namePlaceholder: 'e.g., 15mm Copper Pipe',
      supplierPlaceholder: 'e.g., Heatmerchants',
    },
    onboarding: {
      employeeIcon: 'fa-hard-hat',
      employeeLabel: 'Add Employees',
      showMaterialsStep: true,
      companyContextPlaceholder: 'Examples:\n- Free parking available behind the building\n- Family-run business since 2005\n- All technicians are fully insured\n- 12-month warranty on all work',
    },
  },

  salon: {
    label: 'Salon & Barbershop',
    terminology: {
      job: 'Appointment',
      jobs: 'Appointments',
      employee: 'Stylist',
      employees: 'Stylists',
      client: 'Client',
      clients: 'Clients',
      service: 'Service',
      services: 'Services',
      booking: 'Appointment',
      servicesTab: 'Services',
      inventoryTab: 'Products',
      financesTab: 'Finances',
      insightsTab: 'Insights',
      calendarTab: 'Calendar',
      callsTab: 'Calls',
      crmTab: 'CRM',
    },
    features: {
      materials: true,
      callouts: false,
      quotes: false,
      emergencyJobs: false,
      propertyType: false,
      jobAddress: false,
      jobPhotos: false,
      multiDayJobs: false,
    },
    tabs: {
      jobs: true,
      calls: true,
      calendar: true,
      employees: true,
      crm: true,
      services: true,
      inventory: true,
      finances: true,
      insights: true,
    },
    icons: {
      employee: 'fas fa-user-tie',
      job: 'fas fa-calendar-check',
    },
    serviceConfig: {
      categories: [
        'Haircuts', 'Colour', 'Styling', 'Treatments', 'Nails',
        'Skincare', 'Waxing', 'Makeup', 'Bridal', 'Other',
      ],
      tagPresets: [
        'Vegan Products', 'Organic', 'Ammonia-Free', 'Patch Test Required',
        'Consultation Needed', 'Add-On Service', 'Premium',
        'Walk-In Available', 'By Appointment Only',
      ],
      tagLabel: 'Service Tags',
      tagPlaceholder: 'e.g., Vegan Products, Premium',
      showCategory: true,
      showTags: true,
      showCapacity: false,
      showArea: false,
      showDeposit: true,
      showWarranty: false,
      showSeasonal: false,
      showAiNotes: true,
      showFollowUp: true,
      capacityLabel: '',
      capacityMinLabel: '',
      capacityMaxLabel: '',
      areaLabel: '',
      areaOptions: [],
      warrantyLabel: '',
      warrantyPlaceholder: '',
      depositLabel: 'Deposit Required',
      depositHint: 'Require a deposit before confirming the appointment',
      seasonalLabel: '',
      seasonalHint: '',
      aiNotesLabel: 'Notes for AI',
      aiNotesPlaceholder: 'e.g., Always recommend a patch test 48hrs before, upsell conditioning treatment',
      followUpLabel: 'Follow-up Service',
      followUpHint: 'Suggest this service as a follow-up (e.g., toner after colour)',
      durationGroups: ['Hours'],
      defaultServiceIcon: 'fa-cut',
      emptyIcon: '💇',
      emptyTitle: 'No services yet',
      emptyDescription: 'Add the services you offer. The AI receptionist will use these to match client requests and book appointments.',
    },
    inventory: {
      categories: [
        'Hair Colour', 'Shampoo & Conditioner', 'Styling Products', 'Treatments',
        'Tools & Accessories', 'Towels & Capes', 'Retail Products',
        'Cleaning Supplies', 'Disposables', 'Other',
      ],
      units: [
        { value: 'each', label: 'Each' },
        { value: 'ml', label: 'Millilitre (ml)' },
        { value: 'litre', label: 'Litre' },
        { value: 'g', label: 'Gram (g)' },
        { value: 'kg', label: 'Kilogram (kg)' },
        { value: 'tube', label: 'Tube' },
        { value: 'bottle', label: 'Bottle' },
        { value: 'box', label: 'Box' },
        { value: 'pack', label: 'Pack' },
        { value: 'set', label: 'Set' },
        { value: 'pair', label: 'Pair' },
        { value: 'roll', label: 'Roll' },
      ],
      showCostPrice: true,
      showExpiry: true,
      showBatchNumber: true,
      showLocation: true,
      locationLabel: 'Storage',
      locationPlaceholder: 'e.g., Station 1, Back Room, Display',
      itemLabel: 'Product',
      emptyIcon: '💇',
      emptyTitle: 'No products yet',
      emptyDescription: 'Add the products and supplies you use. Track stock, costs, and set reorder alerts.',
      namePlaceholder: 'e.g., Olaplex No.3',
      supplierPlaceholder: 'e.g., Salon Services',
    },
    onboarding: {
      employeeIcon: 'fa-user-tie',
      employeeLabel: 'Add Stylists',
      showMaterialsStep: true,
      companyContextPlaceholder: 'Examples:\n- Walk-ins welcome\n- Free WiFi and complimentary drinks\n- Specialising in colour and balayage\n- Late opening Thursdays until 9pm',
    },
  },

  cleaning: {
    label: 'Cleaning Services',
    terminology: {
      job: 'Job',
      jobs: 'Jobs',
      employee: 'Cleaner',
      employees: 'Cleaners',
      client: 'Customer',
      clients: 'Customers',
      service: 'Service',
      services: 'Services',
      booking: 'Booking',
      servicesTab: 'Services',
      inventoryTab: 'Supplies',
      financesTab: 'Finances',
      insightsTab: 'Insights',
      calendarTab: 'Calendar',
      callsTab: 'Calls',
      crmTab: 'CRM',
    },
    features: {
      materials: true,
      callouts: false,
      quotes: true,
      emergencyJobs: false,
      propertyType: true,
      jobAddress: true,
      jobPhotos: false,
      multiDayJobs: false,
    },
    tabs: {
      jobs: true,
      calls: true,
      calendar: true,
      employees: true,
      crm: true,
      services: true,
      inventory: true,
      finances: true,
      insights: true,
    },
    icons: {
      employee: 'fas fa-broom',
      job: 'fas fa-briefcase',
    },
    serviceConfig: {
      categories: [
        'Residential', 'Commercial', 'Deep Clean', 'End of Tenancy',
        'Carpet & Upholstery', 'Window Cleaning', 'Pressure Washing',
        'Office', 'One-Off', 'Other',
      ],
      tagPresets: [
        'Eco-Friendly', 'Pet-Friendly', 'Supplies Included', 'Insured',
        'Recurring Available', 'Same Day', 'Weekend Available',
        'After Hours', 'Key Holder',
      ],
      tagLabel: 'Service Tags',
      tagPlaceholder: 'e.g., Eco-Friendly, Supplies Included',
      showCategory: true,
      showTags: true,
      showCapacity: false,
      showArea: false,
      showDeposit: true,
      showWarranty: false,
      showSeasonal: true,
      showAiNotes: true,
      showFollowUp: true,
      capacityLabel: '',
      capacityMinLabel: '',
      capacityMaxLabel: '',
      areaLabel: '',
      areaOptions: [],
      warrantyLabel: '',
      warrantyPlaceholder: '',
      depositLabel: 'Deposit Required',
      depositHint: 'Require a deposit before confirming the booking',
      seasonalLabel: 'Seasonal Service',
      seasonalHint: 'Only available during certain months (e.g., spring clean)',
      aiNotesLabel: 'Notes for AI',
      aiNotesPlaceholder: 'e.g., Always ask about pets, confirm parking access',
      followUpLabel: 'Follow-up Service',
      followUpHint: 'Suggest this service after the initial clean',
      durationGroups: ['Hours', 'Days'],
      defaultServiceIcon: 'fa-broom',
      emptyIcon: '🧹',
      emptyTitle: 'No services yet',
      emptyDescription: 'Add the cleaning services you offer. The AI receptionist will use these to match customer requests and book jobs.',
    },
    inventory: {
      categories: [
        'Cleaning Solutions', 'Disinfectants', 'Floor Care', 'Glass & Surface',
        'Tools & Equipment', 'Cloths & Wipes', 'Bin Bags & Liners',
        'Paper Products', 'Safety & PPE', 'Fragrances', 'Other',
      ],
      units: [
        { value: 'each', label: 'Each' },
        { value: 'litre', label: 'Litre' },
        { value: 'ml', label: 'Millilitre (ml)' },
        { value: 'bottle', label: 'Bottle' },
        { value: 'box', label: 'Box' },
        { value: 'pack', label: 'Pack' },
        { value: 'roll', label: 'Roll' },
        { value: 'bag', label: 'Bag' },
        { value: 'pair', label: 'Pair' },
        { value: 'kg', label: 'Kilogram (kg)' },
      ],
      showCostPrice: true,
      showExpiry: false,
      showBatchNumber: false,
      showLocation: true,
      locationLabel: 'Location',
      locationPlaceholder: 'e.g., Van, Supply Room, Client Site',
      itemLabel: 'Supply',
      emptyIcon: '🧹',
      emptyTitle: 'No supplies yet',
      emptyDescription: 'Add the cleaning supplies and products you use. Track stock and set reorder alerts.',
      namePlaceholder: 'e.g., All-Purpose Cleaner 5L',
      supplierPlaceholder: 'e.g., Hygiene Supplies Ltd',
    },
    onboarding: {
      employeeIcon: 'fa-broom',
      employeeLabel: 'Add Cleaners',
      showMaterialsStep: true,
      companyContextPlaceholder: 'Examples:\n- Eco-friendly products used\n- All staff are Garda vetted\n- We bring all our own supplies\n- End-of-tenancy deep cleans available',
    },
  },

  restaurant: {
    label: 'Restaurant & Café',
    terminology: {
      job: 'Reservation',
      jobs: 'Reservations',
      employee: 'Server',
      employees: 'Staff',
      client: 'Guest',
      clients: 'Guests',
      service: 'Menu Item',
      services: 'Menu',
      booking: 'Reservation',
      servicesTab: 'Menu',
      inventoryTab: 'Stock',
      financesTab: 'Finances',
      insightsTab: 'Insights',
      calendarTab: 'Reservations',
      callsTab: 'Calls',
      crmTab: 'Guests',
    },
    features: {
      materials: true,
      callouts: false,
      quotes: false,
      emergencyJobs: false,
      propertyType: false,
      jobAddress: false,
      jobPhotos: false,
      multiDayJobs: false,
      menuDesigner: true,       // Restaurant-only: visual menu builder + PDF export
      tableManagement: true,    // Restaurant-only: table/seating management
    },
    tabs: {
      jobs: true,
      calls: true,
      calendar: true,
      employees: true,
      crm: true,
      services: true,
      inventory: true,
      finances: true,
      insights: true,
    },
    icons: {
      employee: 'fas fa-utensils',
      job: 'fas fa-calendar-check',
    },
    serviceConfig: {
      categories: [
        'Starters', 'Mains', 'Desserts', 'Sides', 'Drinks',
        'Wine', 'Cocktails', 'Kids Menu', 'Set Menu', 'Specials',
        'Breakfast', 'Brunch', 'Lunch', 'Dinner', 'Late Night',
        'Private Dining', 'Events', 'Takeaway', 'Catering', 'Other',
      ],
      tagPresets: [
        'Vegetarian', 'Vegan', 'Gluten-Free', 'Nut-Free', 'Halal',
        'Kosher', 'Dairy-Free', 'Spicy', 'Chef\'s Choice', 'Popular',
        'Set Menu', 'À La Carte',
        'Outdoor Seating', 'High Chair Available', 'Wheelchair Accessible',
      ],
      tagLabel: 'Dietary & Amenity Tags',
      tagPlaceholder: 'e.g., Vegetarian, Gluten-Free',
      showCategory: true,
      showTags: true,
      showCapacity: true,        // party size / covers
      showArea: true,             // table section / area
      showDeposit: true,
      showWarranty: false,
      showSeasonal: true,
      showAiNotes: true,
      showFollowUp: false,
      capacityLabel: 'Party Size',
      capacityMinLabel: 'Min guests',
      capacityMaxLabel: 'Max guests',
      areaLabel: 'Dining Area',
      areaOptions: [
        'Indoor', 'Outdoor', 'Private Room', 'Bar', 'Terrace',
        'Rooftop', 'Garden', 'Any',
      ],
      warrantyLabel: '',
      warrantyPlaceholder: '',
      depositLabel: 'Deposit Required',
      depositHint: 'Require a deposit for this reservation type (e.g., large parties, events)',
      seasonalLabel: 'Seasonal / Limited',
      seasonalHint: 'Only available during certain months (e.g., Christmas menu, summer terrace)',
      aiNotesLabel: 'Notes for AI',
      aiNotesPlaceholder: 'e.g., Always mention set menu for groups of 8+, ask about dietary requirements',
      followUpLabel: '',
      followUpHint: '',
      durationGroups: ['Hours'],
      defaultServiceIcon: 'fa-utensils',
      emptyIcon: '🍽️',
      emptyTitle: 'No menu items yet',
      emptyDescription: 'Add your menu items, dining services, and reservation types. The AI receptionist will use these to match guest requests and book reservations.',
      // Menu designer config
      menuDesigner: {
        enabled: true,
        paperSizes: ['A4', 'Letter', 'A5'],
        defaultPaperSize: 'A4',
        themes: [
          { id: 'classic', label: 'Classic', fontFamily: 'Georgia, serif', accentColor: '#2c2c2c' },
          { id: 'modern', label: 'Modern', fontFamily: "'Helvetica Neue', sans-serif", accentColor: '#1a1a2e' },
          { id: 'elegant', label: 'Elegant', fontFamily: "'Playfair Display', serif", accentColor: '#4a0e0e' },
          { id: 'rustic', label: 'Rustic', fontFamily: "'Courier New', monospace", accentColor: '#5c4033' },
          { id: 'minimal', label: 'Minimal', fontFamily: "'Inter', sans-serif", accentColor: '#333333' },
        ],
        defaultTheme: 'classic',
        showPrices: true,
        showDescriptions: true,
        showDietaryTags: true,
        headerFields: ['restaurantName', 'tagline', 'logo'],
        footerFields: ['address', 'phone', 'website', 'allergenNotice'],
        defaultAllergenNotice: 'Please inform your server of any allergies or dietary requirements.',
      },
    },
    inventory: {
      categories: [
        'Proteins', 'Produce', 'Dairy & Eggs', 'Dry Goods & Grains',
        'Beverages', 'Alcohol', 'Oils & Condiments', 'Frozen',
        'Bakery & Bread', 'Cleaning & Chemicals', 'Packaging & Takeaway',
        'Tableware & Utensils', 'Other',
      ],
      units: [
        { value: 'each', label: 'Each' },
        { value: 'kg', label: 'Kilogram (kg)' },
        { value: 'g', label: 'Gram (g)' },
        { value: 'litre', label: 'Litre' },
        { value: 'ml', label: 'Millilitre (ml)' },
        { value: 'bottle', label: 'Bottle' },
        { value: 'case', label: 'Case' },
        { value: 'box', label: 'Box' },
        { value: 'pack', label: 'Pack' },
        { value: 'bag', label: 'Bag' },
        { value: 'tin', label: 'Tin' },
        { value: 'dozen', label: 'Dozen' },
        { value: 'portion', label: 'Portion' },
        { value: 'keg', label: 'Keg' },
      ],
      showCostPrice: true,
      showExpiry: true,
      showBatchNumber: true,
      showLocation: true,
      locationLabel: 'Storage',
      locationPlaceholder: 'e.g., Walk-in Fridge, Dry Store, Freezer, Bar',
      itemLabel: 'Ingredient',
      emptyIcon: '🍽️',
      emptyTitle: 'No stock items yet',
      emptyDescription: 'Add your ingredients, beverages, and supplies. Track stock levels, expiry dates, and costs.',
      namePlaceholder: 'e.g., Chicken Breast 5kg',
      supplierPlaceholder: 'e.g., Musgrave MarketPlace',
    },
    onboarding: {
      employeeIcon: 'fa-utensils',
      employeeLabel: 'Add Staff',
      showMaterialsStep: true,
      companyContextPlaceholder: 'Examples:\n- Outdoor seating available\n- Vegetarian and vegan options\n- Private dining room for events\n- Free parking on site',
    },
  },
};

export default industryProfiles;
